export const AUTH = {
  UPDATE_FIRSTNAME: "UPDATE_FIRSTNAME",
  UPDATE_LASTNAME: "UPDATE_LASTNAME",
  UPDATE_EMAIL: "UPDATE_EMAIL",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  UPDATE_FILEPATH: "UPDATE_FILEPATH",
  UPDATE_USER_TOKEN: "UPDATE_USER_TOKEN",
  UPDATE_USER_INFO: [],
};

export const PRODUCT = {
  UPDATE_PRODUCT_ID: "UPDATE_PRODUCT_ID",
  UPDATE_PROD_NAME: "UPDATE_PROD_NAME",
  UPDATE_PROD_DESC: "UPDATE_PROD_DESC",
  UPDATE_PROD_PRICE: "UPDATE_PROD_PRICE",
  UPDATE_PROD_CAT_ID: "UPDATE_PROD_CAT_ID",
  UPDATE_PROD_IMAGE: "UPDATE_PROD_IMAGE",
  UPDATE_PROD_LIST: [],
  UPDATE_PROD_INFO: [],
};

export const CATEGORY = {
  UPDATE_CATEGORY_ID: "UPDATE_CATEGORY_ID",
  UPDATE_CATEGORY_NAME: "UPDATE_CATEGORY_NAME",
  UPDATE_CATEGORY_LIST: [],
};

export const NAVSEARCH = {
  UPDATE_NAV_SEARCH: "UPDATE_NAV_SEARCH",
};

export const CART = {
  UPDATE_CART_ID: "UPDATE_CART_ID",
  UPDATE_CART_PROD_ID: "UPDATE_CART_PROD_ID",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  UPDATE_CART_USER_ID: "UPDATE_CART_USER_ID",
  UPDATE_CARTLIST: "UPDATE_CARTLIST",
  UPDATE_ORDERLIST: "UPDATE_ORDERLIST",
};

export const ORDER = {
  UPDATE_ALL_ORDERS: [],
}
